import = ["/home/adrian/.config/alacritty/theme.toml"]

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
key = "T"
mods = "Control"

[keyboard.bindings.command]
program = "/home/adrian/.config/alacritty/themeswitch.sh"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[window.dimensions]
columns = 90
lines = 30
